default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: mysql2
  encoding: utf8mb4
  database: livehub_development
  host: <%= ENV.fetch("MYSQL_HOST", "127.0.0.1") %>
  username: <%= ENV.fetch("MYSQL_USERNAME", "root") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD", "") %>

test:
  <<: *default
  adapter: mysql2
  encoding: utf8mb4
  database: livehub_test
  host: <%= ENV.fetch("MYSQL_HOST", "127.0.0.1") %>
  username: <%= ENV.fetch("MYSQL_USERNAME", "root") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD", "") %>

production:
  <<: *default
  adapter: mysql2
  encoding: utf8mb4
  url: <%= ENV["MYSQL_URL"] %>